import { makeEnvironmentProviders, type EnvironmentProviders } from '@angular/core';
import { provideIcons } from '@ng-icons/core';
import {
  lucideActivity,
  lucideArrowLeft,
  lucideBaby,
  lucideChevronRight,
  lucideClock,
  lucideEye,
  lucideEyeOff,
  lucideFence,
  lucideHeartOff,
  lucideHouse,
  lucideInbox,
  lucideLoaderCircle,
  lucideLock,
  lucideLogOut,
  lucideMail,
  lucideMoveHorizontal,
  lucidePackage,
  lucidePawPrint,
  lucidePencil,
  lucidePlus,
  lucideSearch,
  lucideSyringe,
  lucideTractor,
  lucideTrash2,
  lucideTriangleAlert,
} from '@ng-icons/lucide';
import { speciesGoat, speciesPig, speciesSheep } from './species-icons';

export const LUCIDE_ICONS = {
  lucideActivity,
  lucideArrowLeft,
  lucideBaby,
  lucideChevronRight,
  lucideClock,
  lucideEye,
  lucideEyeOff,
  lucideFence,
  lucideHeartOff,
  lucideHouse,
  lucideInbox,
  lucideLoaderCircle,
  lucideLock,
  lucideLogOut,
  lucideMail,
  lucideMoveHorizontal,
  lucidePackage,
  lucidePawPrint,
  lucidePencil,
  lucidePlus,
  lucideSearch,
  lucideSyringe,
  lucideTractor,
  lucideTrash2,
  lucideTriangleAlert,
  speciesGoat,
  speciesPig,
  speciesSheep,
};

export const provideLucideIcons = (): EnvironmentProviders =>
  makeEnvironmentProviders(provideIcons(LUCIDE_ICONS));
