import { makeEnvironmentProviders, type EnvironmentProviders } from '@angular/core';
import { provideIcons } from '@ng-icons/core';
import {
  lucideActivity,
  lucideArrowLeft,
  lucideBaby,
  lucideCalendar,
  lucideChevronRight,
  lucideCircleCheck,
  lucideClock,
  lucideDownload,
  lucideEllipsis,
  lucideFence,
  lucideHeartOff,
  lucideHouse,
  lucideInbox,
  lucideMapPin,
  lucideMoveHorizontal,
  lucidePackage,
  lucidePawPrint,
  lucidePencil,
  lucidePlus,
  lucideSearch,
  lucideSyringe,
  lucideTrash2,
  lucideTriangleAlert,
  lucideUpload,
  lucideWifi,
  lucideWifiOff,
} from '@ng-icons/lucide';

export const LUCIDE_ICONS = {
  lucideActivity,
  lucideArrowLeft,
  lucideBaby,
  lucideCalendar,
  lucideChevronRight,
  lucideCircleCheck,
  lucideClock,
  lucideDownload,
  lucideEllipsis,
  lucideFence,
  lucideHeartOff,
  lucideHouse,
  lucideInbox,
  lucideMapPin,
  lucideMoveHorizontal,
  lucidePackage,
  lucidePawPrint,
  lucidePencil,
  lucidePlus,
  lucideSearch,
  lucideSyringe,
  lucideTrash2,
  lucideTriangleAlert,
  lucideUpload,
  lucideWifi,
  lucideWifiOff,
};

export const provideLucideIcons = (): EnvironmentProviders =>
  makeEnvironmentProviders(provideIcons(LUCIDE_ICONS));
